### ISSUE TITLE
Fix compilation and guis on macOS

### ISSUE THREAD

**Issue by ftessier** [nrc-cnrc/EGSnrc#704]
This is issue is replacing a few recently closed issues regarding macOS compilation, which has become increasingly difficult in the past few years. I will integrate here the individual issues that have been reported in this regard:

- [x] #150 PreviewRZ does not work on macOS
- [x] #325 Issue compiling egs_view on macOS Sierra
- [x] #642 EGSnrc installation issue on Mac OS Catalina 10.15.7
- [x] #671 Mac OS Big Sur configuration Error
- [x] #644 EGSnrc installation issue during compiling egs_view on mac os catalina 10.15.5

**Comment by SashaSn** [comment]
Hi! Could you please help me with the issue:

**Comment by SashaSn** [comment]
Hi! Could you please help me with the issue: 
Input fortran compiler:                           [gfortran] 
Testing if gfortran works ...                     yes. Object extension is 'o'
Testing if gfortran can create executables ...    no
error: this FORTRAN compiler can not create executables!

I am using MacOs BigSur  Version 11.5.2  Macbook Air (M1 2020) 
gfortran GNU Fortran (GCC) 5.1.0

Is there any workaround? 
Thank you in advance!

**Comment by ftessier** [comment]
Please consult the updated [macOS installation instructions](https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS), which are known to work on macOS 11 (Big Sur).

**Comment by erjft** [comment]
Hi Fred 

I'm using Apple M1 Pro, macOS Sequoia Version 15.1 with https://github.com/nrc-cnrc/EGSnrc/wiki/Install-EGSnrc-on-macOS. I downloaded and did the git installation instructions both result in this error seen above (see below too):

First step was:

`./HEN_HOUSE/scripts/configure`

```
Checking system type ...                          arm-apple-darwin24.1.0
Checking for make ...                             yes (/opt/homebrew/bin/gmake)

Looking for available fortran compilers ...       found: gfortran

Input fortran compiler:                           [gfortran] 
Testing if gfortran works ...                     yes. Object extension is 'o'
Testing if gfortran can create executables ...    no
error: this FORTRAN compiler can not create executables!
```

the ~/.bashrc and ~/.zshrc are empty of HEN_HOUSE, EGS_HOME and EGS_CONFIG path values

```
**gfortran --version:**
GNU Fortran (MacPorts gcc12 12.3.0_4+stdlib_flag) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**gcc --version:**
gcc (MacPorts gcc12 12.3.0_4+stdlib_flag) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**g++ --version:**
g++ (MacPorts gcc12 12.3.0_4+stdlib_flag) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**make --version:**
GNU Make 4.4.1
Built for aarch64-apple-darwin21.6.0
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
changing the gcc version and g++ version from the MacPorts ones to Homebrew GCC 14.2.0_1, and installs with errors:

```
Compiling ctcreate ...                            Failed
Compiling statdose ...                            OK
Compiling readphsp ...                            OK
Compiling dosxyz_show ...                         Failed
Compiling addphsp ...                             OK

Looking for installed C++ compilers ...           OK

Found the following C++ compilers in your search path:
    g++ CC KCC RCC gpp

Input C++ compiler:                               [g++]: 

The C++ configuration file egspp_osx.conf already exists!
Do you want to overwrite? (yes/no)                yes
sed: 1: ":/:_:g": unused label '/:_:g'
```
